---
# file: Top level playbook, playbook.yml

# Start of the playbook after the minus sign
- hosts: multi
  sudo: yes
  pre_tasks:
    - name: Add mesosphere deb repository keys
      apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

    - name: Install mesosphere deb repository
      apt_repository: repo="deb http://repos.mesosphere.io/ubuntu trusty main" state=present

    - name: Update repository cache
      apt: update_cache=yes cache_valid_time=3600

- hosts: master
  sudo: yes
  pre_tasks:
    - name: Enable haproxy ppa
      apt_repository: repo="ppa:vbernat/haproxy-1.5" state=present

    - name: Install java 8 repository
      apt_repository: repo="ppa:webupd8team/java"

    - name: Update repository cache
      apt: update_cache=yes cache_valid_time=3600

- hosts: slave
  sudo: yes
  pre_tasks:
    - name: Add docker deb repository keys
      apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Remove (legacy) docker deb repository
      apt_repository: repo="deb http://get.docker.io/ubuntu docker main" state=absent

    - name: Add docker deb repository
      apt_repository: repo="deb http://apt.dockerproject.org/repo ubuntu-trusty main" state=present

    - name: Update repository cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - slave
    - common

- hosts: master
  sudo: yes

  roles:
    - master
    - common
