---
- name: restart mesos-slave
  service:
    name: mesos-slave
    enabled: true
    state: restarted

- name: stop mesos-slave
  service:
    name: mesos-slave
    state: stopped
    enabled: false

- name: restart zookeeper
  service:
    name: zookeeper
    enabled: true
    state: restarted

- name: restart mesos-master
  service:
    name: mesos-master
    enabled: true
    state: restarted

- name: restart marathon
  service:
    name: marathon
    enabled: true
    state: restarted
