---
# handlers file for slave

- name: restart mesos-slave
  service:
    name: mesos-slave
    enabled: true
    state: restarted

- name: stop mesos-slave
  service:
    name: mesos-slave
    state: stopped
    enabled: false
