---
# tasks file for slave
- name: Install mesos
  apt: name=mesos state=present

- name: Remove legacy docker package
  apt: name=lxc-docker state=absent purge=yes

- name: Install docker engine
  apt: name=docker-engine state=present

- name: Stop and disable zookeeper in slave nodes
  service:
    name: zookeeper
    enabled: no
    state: stopped

- name: Stop and disable mesos-master in slave nodes
  service:
    name: mesos-master
    enabled: no
    state: stopped

- name: Setup ip for mesos-slave
  template:
    src=ip.j2
    dest=/etc/mesos-slave/ip
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-slave

- name: Setup hostname for mesos-slave
  template:
    src=hostname.j2
    dest=/etc/mesos-slave/hostname
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-slave

- name: Enable docker containerizer
  template:
    src=containerizers.j2
    dest=/etc/mesos-slave/containerizers
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-slave

- name: Increase mesos-slave executor timeout (delay when pulling docker slave)
  template:
    src=executor_registration_timeout.j2
    dest=/etc/mesos-slave/executor_registration_timeout
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-slave
