---
# tasks file for master

- include: dependencies.yml

- name: Stop and disable mesos-slave in master nodes
  service:
    name: mesos-slave
    enabled: false
    state: stopped

- name: Setup zookeeper server ID
  template:
    src=zk.id.j2
    dest=/etc/zookeeper/conf/myid
    owner=root
    group=root
    mode=0644
  notify:
    - restart zookeeper

- name: Setup zookeeper zoo.cfg
  template:
    src=zoo.cfg.j2
    dest=/etc/zookeeper/conf/zoo.cfg
    owner=root
    group=root
    mode=0644
  notify:
    - restart zookeeper

- name: Setup quorum for mesos-master
  template:
    src=quorum.j2
    dest=/etc/mesos-master/quorum
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Setup ip for mesos-master
  template:
    src=ip.j2
    dest=/etc/mesos-master/ip
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Setup hostname for mesos-master
  template:
    src=hostname.j2
    dest=/etc/mesos-master/hostname
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Create directory for marathon configuration
  file:
    path: /etc/marathon/conf
    state: directory
  notify:
    - restart marathon

- name: Configure hostname for marathon configuration
  template:
    src=hostname.j2
    dest=/etc/marathon/conf/hostname
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Configure zookeeper addresses to marathon
  template:
    src=zk.j2
    dest=/etc/marathon/conf/master
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Setup zookeeper addresses on marathon
  template:
    src=marathon.j2
    dest=/etc/marathon/conf/zk
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Increase marathon executor timeout
  template:
    src=marathon_task_launch_timeout.j2
    dest=/etc/marathon/conf/task_launch_timeout
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Enable HTTP callbacks in marathon
  template:
    src=event_subscriber.j2
    dest=/etc/marathon/conf/event_subscriber
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Make sure haproxy /var/run/haproxy folder exists
  file:
    path: /var/run/haproxy
    state: directory

- name: Set GOPATH for all users
  template:
    src=go-path.j2
    dest=/etc/profile.d/go-path.sh
    owner=root
    group=root
    mode=0755

- name: Add bamboo config .json
  template:
    src=bamboo_config.j2
    dest=/var/bamboo/production.json
    owner=root
    group=root
    mode=0644
  notify:
    - restart bamboo

- name: Configure haproxy template used by bamboo
  copy:
    src=haproxy_template.cfg
    dest=/var/bamboo/haproxy_template.cfg
    owner=root
    group=root
    mode=0644
  notify:
    - restart bamboo
