---
# tasks file for master
- name: Install mesosphere
  apt: name=mesosphere state=present

- name: Setup zookeeper server ID
  template:
    src=zk.id.j2
    dest=/etc/zookeeper/conf/myid
    owner=root
    group=root
    mode=0644
  notify:
    - restart zookeeper

- name: Setup zookeeper zoo.cfg
  template:
    src=zoo.cfg.j2
    dest=/etc/zookeeper/conf/zoo.cfg
    owner=root
    group=root
    mode=0644
  notify:
    - restart zookeeper

- name: Setup quorum for mesos-master
  template:
    src=quorum.j2
    dest=/etc/mesos-master/quorum
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Setup ip for mesos-master
  template:
    src=ip.j2
    dest=/etc/mesos-master/ip
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Setup hostname for mesos-master
  template:
    src=hostname.j2
    dest=/etc/mesos-master/hostname
    owner=root
    group=root
    mode=0644
  notify:
    - restart mesos-master

- name: Create directory for marathon configuration
  file:
    path: /etc/marathon/conf
    state: directory
  notify:
    - restart marathon

- name: Copy mesos-master hostnames to marathon configuration
  command: cp /etc/mesos-master/hostname /etc/marathon/conf/
  notify:
    - restart marathon

- name: Copy mesos-master zookeeper addresses to marathon
  command: cp /etc/mesos/zk /etc/marathon/conf/master
  notify:
    - restart marathon

- name: Setup zookeeper addresses on marathon
  template:
    src=marathon.j2
    dest=/etc/marathon/conf/zk
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon

- name: Increase marathon executor timeout
  template:
    src=marathon_task_launch_timeout.j2
    dest=/etc/marathon/conf/task_launch_timeout
    owner=root
    group=root
    mode=0644
  notify:
    - restart marathon
